Задачу о поиске наибольшей подматрицы разобъем на две подзадачи: 
- поиск максимального по площади прямоугольника в гистограмме https://leetcode.com/problems/largest-rectangle-in-histogram/description/
- для каждой строки матрицы запустим поиск прямоугольника в гистограмме

Также выполним предподсчет для исходной матрицы: для каждой ячейки $a[i][j]$ будем хранить число, равное числу единичек над элементом $a[i][j]$ вместе с самой единичкой $a[i][j]$. То есть если обозначить матрицу предподсчета за $d[i][j]$, то

$$
d[i][j] = 
\begin{cases}
d[i-1][j] + 1, & \text{if} \ d[i][j] = 1 \\
0, & \text{otherwise}
\end{cases}
$$

Поиск прямоугольника в гистограмме выполняем за $O(n)$. Запустив $m$ раз поиск прямоугольника на $m$ строках матрицы, получим сложность $O(mn)$, т.е. линейную по размеру входа.

Затраты по доп памяти: $O(n)$ на хранение стека во время поиска прямоугольника в гистограмме, где $n$ - число столбцов в гистограмме.

In [1]:
import numpy as np

In [2]:
def get_max_area_in_histogram(hist):
    """
    find the biggest rectangle in a histogram problem
    """
    stack = []
    max_area_of_rectangle = 0
    
    tos = 0 # top of stack
    area_with_current_tos = 0
    
    left_corner = 0
    right_corner = 0

    index_of_bar = 0 
    while (index_of_bar < len(hist)):
        if ((len(stack) == 0) or (hist[stack[-1]] <= hist[index_of_bar])):
            stack.append(index_of_bar)
            index_of_bar += 1
        else:
            tos = stack.pop()
            
            area_with_current_tos = hist[tos] * \
                            (index_of_bar if len(stack) == 0 else index_of_bar - stack[-1] - 1)

            if area_with_current_tos > max_area_of_rectangle:
                max_area_of_rectangle = area_with_current_tos
                right_corner = index_of_bar
                if len(stack) == 0:
                    left_corner = 0
                else:
                    left_corner = stack[-1] + 1

    while (len(stack) != 0):
        tos = stack.pop()
        area_with_current_tos = hist[tos] * (
            index_of_bar if (len(stack) == 0) else index_of_bar - stack[-1] - 1)

        if area_with_current_tos > max_area_of_rectangle:
            max_area_of_rectangle = area_with_current_tos
            right_corner = index_of_bar
            if len(stack) == 0:
                    left_corner = 0
            else:
                left_corner = stack[-1] + 1
            
    return_list = [max_area_of_rectangle, left_corner, right_corner]
    return return_list

In [3]:
def matrix_preprocessing(matrix):
    for i in range(1, len(matrix)):
        for j in range(len(matrix[0])):
            if matrix[i][j] != 0:
                matrix[i][j] = matrix[i-1][j] + 1
    return matrix

In [4]:
def find_biggest_rectangle_submatrix(matrix):
    matrix_preprocessing(matrix)    
    max_area = 0
    upper_left_corner = 0
    down_right_corner = 0
    row_coordinate = 0
    for row in matrix:
        result = get_max_area_in_histogram(row)
        if result[0] > max_area:
            max_area = result[0]
            left_corner = result[1]
            right_corner = result[2]
            row_number = row_coordinate
        row_coordinate += 1
        
    y_1 = row_number+1 - int(max_area/(right_corner - left_corner))
        
    print("max area of 1's rectangle submatrix is", max_area)
    print("left corner:", (y_1 + 1, left_corner+1))
    print("right corner:", (row_number + 1, right_corner))


In [9]:
M = 4
N = 4
matrix = np.random.randint(0, 2, size=(M, N))
print(matrix)

[[1 0 0 0]
 [1 1 0 1]
 [0 0 1 1]
 [0 0 1 1]]


In [10]:
find_biggest_rectangle_submatrix(matrix)

max area of 1's rectangle submatrix is 4
left corner: (3, 3)
right corner: (4, 4)
